
println "AWS_REGION ${env.AWS_REGION}"
println "AWS_ACCOUNT_ID ${env.AWS_ACCOUNT_ID}"
println "DOCKER_BUILD_SPOT_INST_LABEL ${env.DOCKER_BUILD_SPOT_INST_LABEL}"
println "AWS_REGION ${AWS_REGION}"
println "AWS_ACCOUNT_ID ${AWS_ACCOUNT_ID}"
println "DOCKER_BUILD_SPOT_INST_LABEL ${DOCKER_BUILD_SPOT_INST_LABEL}"

node {
  stage('Checkout') {
    def scmVars = checkout([
      $class: 'GitSCM',
      branches: scm.branches,
      extensions: scm.extensions,
      userRemoteConfigs: [
        [
          credentialsId: scm.userRemoteConfigs[0].credentialsId,
          name: 'origin',
          refspec: '+refs/heads/*:refs/remotes/origin/*',
          url: scm.userRemoteConfigs[0].url
        ]
      ],
    ])
    println "AWS_REGION ${AWS_REGION}"
    println "AWS_ACCOUNT_ID ${AWS_ACCOUNT_ID}"
    println "DOCKER_BUILD_SPOT_INST_LABEL ${DOCKER_BUILD_SPOT_INST_LABEL}"
  }
}
