node {

  stage("Prepare") {
    cleanWs()

    def scmVars = checkout([
      $class: 'GitSCM',
      branches: scm.branches,
      extensions: scm.extensions,
      userRemoteConfigs: [
        [
          credentialsId: scm.userRemoteConfigs[0].credentialsId,
          name: 'origin',
          refspec: '+refs/heads/*:refs/remotes/origin/*',
          url: scm.userRemoteConfigs[0].url
        ]
      ],
    ])
  }

  stage('Test') {
      sh """#!/bin/bash
        source ${WORKSPACE}/scripts/another-script.sh
        echo "Hello world from test"
      """
  }

  // stage('Test 2') {
  //   sh """#!/bin/bash
  //     echo "Hello world from test 2"
  //     echo "$DOCKER_IMAGE from different stage"
  //   """
  // }
}